name: Docker Build Test

on:
  push:
    branches:
      - dockerize-toolkit

  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t js-utility-toolkit .

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name js-toolkit js-utility-toolkit

      - name: Test website
        run: |
          sleep 5
          curl --fail http://localhost:8080

      - name: Stop container
        run: docker stop js-toolkit
